### ISSUE TITLE
order_placed_at_min

### ISSUE THREAD

**Issue by petersonryanm** [ordoro/api-examples#1]
Hi, I noticed you use the param order_placed_at_min, but when I look in the docs (and try it), it doesn't seem to exist.  I do see two other date params: created_after and start_order_date.

I am specifically interested in the order endpoint.  Thanks!

**Comment by drmaples** [comment]
i think the correct param you are looking for is `created_after` which will find orders created after the date you specify. i will correct the wiki page.

please reopen this issue if you need anything else.
